### PR TITLE
Moved config loading from constructor to methods

### PR DESCRIPTION
**Pull request by danbovey**
This allows variables to be passed in to the plugin

Fixes issue #141

Changes: Moves `this.config` from constructor to each method that requires use of `dynamodb` config from `custom`.

### CODE REVIEW

**Comment by andrewgadziksonos** [comment]
Can someone review this?  Our team would like to use this.  I can verify that this works

**Review by andrewgadziksonos — APPROVED** [review]

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
@danbovey can you update the branch?

**Comment by danbovey** [comment]
Ah good the test finished this time! Looks like you can no longer access `dataApp.prototype.port` without first instantiating it, so we'll have to mock a serverless service object. Updates to PR incoming...

**Comment by danbovey** [comment]
Omg it's like one check or the other 😅

**Comment by danbovey** [comment]
Would love to get this merged so we can delete our fork. Wonder if codacy picks up new PR comments and reports?

EDIT - Appears not, @rehrumesh please merge manually 😄

**Comment by rehrumesh** [comment]
Hi @danbovey extremely sorry for the delay in merging. This is a really valued addition to the project. Thanks again. We will do a npm update soon after merging rest of the open PRs.

**Comment by jasonlimantoro** [comment]
Hi, I still experience this issue
Can you take a look at it again?

I have taken a look at the source code, I think the issue still exists in the `shouldExecute()` method.
```javascript

    /**
     * To check if the handler needs to be executed based on stage
     *
     * @return {Boolean} if the handler can run for the provided stage
     */
    shouldExecute() {
      if (this.config.stages && this.config.stages.includes(this.stage)) {
        return true;
      }
      return false;
    }
```

It still directly refers to the `this.config` from the constructor.

**Pull request merged**
