### PR TITLE
Add host option

### PR DESCRIPTION
**Pull request by smdern**
Allow users to specify the host. This is helpful when using docker-compose and you're running inside of a container and dynamodb-local is a linked service and you need to specify the service alias as the host.

### CODE REVIEW

**Comment by smdern** [comment]
Resolves https://github.com/99xt/serverless-dynamodb-local/issues/87

**Comment by deanmraz** [comment]
@rehrumesh can we get this merged? This would be super helpful!

**Comment by MichaelDorkhom** [comment]
Can we merge this, please?

**Review by MichaelDorkhom — APPROVED** [review]

**Review by MichaelDorkhom — COMMENTED** [review]
Can we merge this please?

**Review by kinyat — APPROVED** [review]

**Comment by kinyat** [comment]
This is super useful. We want to use the migration and seeding function with our separated dynamoDb local.

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
This is great. Thanks for the PR @smdern . Can you also update the documentation accordingly?

@deanmraz @kinyat NPM is updated. Apologies for the delay.

**Comment by alejodiazg** [comment]
Know this is closed, but the usage is if I see correctly on my serverless.yml

```
custom:
  dynamodb:
    stages:
      - dev
      - local
    start:
      port : 8000
      shareDb: true
      migrate: true
      noStart: true
      host: dockerized-dynamo

```

or I have to forget about the noStart?

**Pull request merged**
