### PR TITLE
Delete ttl from dynamodb table CloudFormation specification

### PR DESCRIPTION
**Pull request by alexzelenuyk**
With the recent release of [CloudFormation](https://aws.amazon.com/about-aws/whats-new/2017/07/aws-cloudformation-coverage-updates-for-amazon-api-gateway--amazon-ec2--amazon-emr--amazon-dynamodb-and-more/?sc_channel=em&sc_campaign=Launch_RN20170711&sc_publisher=aws&sc_medium=em_&sc_content=launch_la_nontier1&sc_country=&sc_geo=&sc_category=mult&sc_outcome=launch&mkt_tok=eyJpIjoiWkRobU1EY3pPREl5WXpNMiIsInQiOiJmZUR0MlFMVFpLZUtvek9mUXN0SjFrWlBEc25uZVdZSGlpdnJwdVlERGk4QnVzeEE0QmttbDg0NkI3RElkU1pDak9rRmwzNlNxdVBUXC9Gb1lyMFo3QUVoV2ZsdDlGbWNFVU9ZT0Vja2dNN3EzQzlXYjkwbkM4all2R3BOeDJnT0kifQ%3D%3D) it supports configuring TTL for dynamodb but this is [not supported](https://forums.aws.amazon.com/thread.jspa?threadID=251088) by dynamodb local.

That's why we need to exclude ttl specification before creating local dynamodb table

### CODE REVIEW

**Comment by HenrikFricke** [comment]
👍

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
@alexzelenuyk does it break if someone have included TTL? I haven't use TTL so far.

**Comment by alexzelenuyk** [comment]
@rehrumesh you can't have ttl in local database anyway only on AWS, that's why it doesn't break

**Comment by rehrumesh** [comment]
@alexzelenuyk Thanks. Can you update the Readme as well. I think then all is set to merge this PR.

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
@alexzelenuyk Thanks for this. I have merged this and will be doing a npm update soon.

**Pull request merged**
