### PR TITLE
Implement v1 branch seeding

### PR DESCRIPTION
**Pull request by darthtrevino**
This commit takes a cut at implementing seeding in the v1 branch. I originally submitted a PR to https://github.com/99xt/dynamodb-migrations/pull/6, but it looks like that project is being deprecated by this version of serverless-dynamodb-local.

My **serverless.yaml** file looks like this:
```yaml
dynamodb:
   start:
     seed: true
   seed:
     domain:
       sources:
       - table: widgets
         sources: [./widget-table-data.json]

     test:
        sources:
        - table: users
          sources: [./fake-test-users.json]
```

```bash
> sls dynamodb seed --seed=domain,test
```
Basically what's going on is that after the tables are spooled up, we will scrape the sources in the for seeds, which represent rows in Dynamo. If the files are arrays, each object is a seed, if the files are objects, then it's a seed.

~~I'd like to think of a way that predicates the loading of these things: My thought ways maybe have a `loadStage` array in each seed config that would conditionally use the sources based on the current stage variable. This would allow users to load stuff like domain data into production databases, but only load mocked up data in development or integration. What do you guys think?~~

I wanted to avoid including the seed data here for a couple of reasons: domain data and test data are not configuration by nature, and in some cases the test data could be pretty large. In my case, I have about 15mb going into a table.

This commit also corrects the promise sequencing and offline-hook setup at startup. I was running into an issue where this plugin would not start up prior to serverless-offline.

### CODE REVIEW

**Comment by darthtrevino** [comment]
The codacy check here is interesting. Most of the issues it has are with single-quote strings, but the code was written with single quote strings already. I can fix that if you guys want, but I think it would make sense to use eslint in the package build itself to ensure that code follows the style you expect.

**Comment by darthtrevino** [comment]
So another option would be to give each seeding source a `category`, and define a runtime opt to seed certain categories. e.g.

```yml
dynamodb:
   start:
     seed: true
   seed:
     locations:
       - table: domain
         sources: [./domain-table-data.json]
         category: domain
       - table: users
         sources: [./fake-test-users.json] 
         category: test
```

And then invoking it:
```sh
> sls dynamodb seed --category=domain,test
```

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
LGTM.  👍 
Thanks @darthtrevino for the wonderful PR.

**Comment by AshanFernando** [comment]
@darthtrevino Thanks for the PR. There are few merge conflict due to delay in merging and the fault is from our side. Will you be able to resolve the conflicts and update the PR?

**Comment by darthtrevino** [comment]
I can resolve the merge conflicts later today

**Comment by darthtrevino** [comment]
This looks okay on my end, let me know if you need anything else

**Comment by nielslanting** [comment]
I use node 4.3.2(The node version AWS Lambda uses) to match my development environment as closely to the live environment as possible. When I use node 7.5.0 it works.

This merge doesn't seem to work with that node version.

`
  Syntax Error -------------------------------------------
     Unexpected token {
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
  Stack Trace --------------------------------------------
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:59:22
    at Array.forEach (native)
    at PluginManager.loadPlugins (C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:58:13)
    at PluginManager.loadServicePlugins (C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:86:10)
    at PluginManager.loadAllPlugins (C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:54:10)
    at C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:64:28
    at process._tickCallback (node.js:364:9)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\bin\serverless:15:28
    at Object.<anonymous> (C:\Users\Niels\AppData\Roaming\npm\node_modules\serverless\bin\serverless:27:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Please report this error. We think it might be a bug.
  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       4.3.2
     Serverless Version: 1.7.0
`

**Comment by darthtrevino** [comment]
@nielslanting That's fair, according to the Node LTS schedule, v4 will be maintained for about another year. After that point, it will make sense to switch to v6 syntax.

**Comment by darthtrevino** [comment]
The `serverless-offline` project was just updated to support a shutdown hook, this PR implements support for the shutdown hook.

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
This is great.

**Comment by darthtrevino** [comment]
When do you think this could be merged into the v1 branch?

**Pull request merged**
