### PR TITLE
(fix) seeding

### PR DESCRIPTION
**Pull request by remicastaing**
The seeding defined in serverless.yml wasn't working.

### CODE REVIEW

**Review by rehrumesh — APPROVED** [review]

**Comment by nenti** [comment]
If we want it to work like that we need to change the readme. Because that way you don't need the `seed: true` config anymore. The root cause of this is that the seed config from `serverless.yml` isn't passed through properly. 

Right now system is working when using `--seed` property in CLI.

**Comment by remicastaing** [comment]
Ok, I got it.

What about:
```const seed = this.options.seed || config.start.seed;```
instead. So you can seed with the `--seed` property in the CLI and also with `seed: true` from `serverless.yml`.

**Comment by nenti** [comment]
Looks good.

**Comment by rehrumesh** [comment]
Thanks @remicastaing

**Pull request merged**
